# Generated by Django 5.2.14 on 2026-05-18 11:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(db_index=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('notes', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ('name',),
                'indexes': [models.Index(fields=['name'], name='customers_c_name_f018e2_idx')],
                'constraints': [models.UniqueConstraint(fields=('phone',), name='uniq_customer_phone')],
            },
        ),
    ]
