from django.urls import path

from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path("order/", views.order_page, name="order"),
    path("checkout/", views.checkout, name="checkout"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("products/", views.products, name="products"),
    path("products/catalog/", views.taxonomy_manage, name="taxonomy_manage"),
    path("products/add/", views.product_create, name="product_create"),
    path("batches/<int:pk>/barcode/", views.batch_barcode_print, name="batch_barcode_print"),
    path("products/<int:pk>/", views.product_detail, name="product_detail"),
    path("customers/", views.customers, name="customers"),
    path("customers/<int:pk>/", views.customer_detail, name="customer_detail"),
    path("suppliers/", views.suppliers, name="suppliers"),
    path("suppliers/<int:pk>/", views.supplier_detail, name="supplier_detail"),
    path("invoices/", views.invoices, name="invoices"),
    path("orders/<int:pk>/", views.order_detail, name="order_detail"),
    path("invoices/<int:pk>/", views.invoice_detail, name="invoice_detail"),
    path("returns/", views.returns, name="returns"),
    path("antibiotics/", views.antibiotic_registers, name="antibiotic_registers"),
    path("reminders/", views.reminders, name="reminders"),
    path("settings/", views.settings_page, name="settings"),
    path("api/search/products/", views.api_product_search, name="api_product_search"),
    path("api/products/<int:pk>/variants/", views.api_product_variants, name="api_product_variants"),
    path("api/cart/add/", views.api_cart_add, name="api_cart_add"),
    path("api/cart/remove/", views.api_cart_remove, name="api_cart_remove"),
    path("api/dashboard/", views.api_dashboard, name="api_dashboard"),
    path("api/qz/certificate/", views.api_qz_certificate, name="api_qz_certificate"),
    path("api/qz/sign/", views.api_qz_sign, name="api_qz_sign"),
    path("sign-qz/", views.sign_qz, name="sign_qz"),
    path("api/printing/settings/", views.api_printer_settings, name="api_printer_settings"),
    path("api/printing/settings/save/", views.api_printer_settings_save, name="api_printer_settings_save"),
    path("api/printing/test-receipt/", views.api_print_test_receipt, name="api_print_test_receipt"),
    path("api/printing/test-label/", views.api_print_test_label, name="api_print_test_label"),
    path("api/invoices/<int:pk>/receipt/", views.api_invoice_receipt, name="api_invoice_receipt"),
    path("api/batches/<int:pk>/qr.png", views.api_batch_qr_png, name="api_batch_qr_png"),
    path("api/batches/<int:pk>/label/", views.api_batch_label, name="api_batch_label"),
]
