# Generated by Django 6.0.5 on 2026-05-18 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbatch',
            name='buy_price_per_box',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='productbatch',
            name='mfg_date',
            field=models.DateField(blank=True, null=True, verbose_name='Manufacturing date'),
        ),
        migrations.AddField(
            model_name='productbatch',
            name='mrp_per_box',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='MRP per box'),
        ),
        migrations.AddField(
            model_name='productbatch',
            name='number_of_boxes',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='productbatch',
            name='tp_price_per_box',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='TP price per box'),
        ),
        migrations.AddField(
            model_name='productbatch',
            name='units_per_box',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
