# Generated by Django 6.0.5 on 2026-05-18 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_productbatch_buy_price_per_box_productbatch_mfg_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbatch',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, max_length=80, null=True, unique=True),
        ),
    ]
