# Generated by Django 6.0.5 on 2026-05-19 00:59

from django.db import migrations, models


def normalize_visible_ids(apps, schema_editor):
    Customer = apps.get_model("pharmacy", "Customer")
    Order = apps.get_model("pharmacy", "Order")
    SalesInvoice = apps.get_model("pharmacy", "SalesInvoice")

    for index, customer in enumerate(Customer.objects.order_by("id"), start=1):
        if customer.customer_code.startswith("CUST"):
            customer.customer_code = f"20260519{index:02d}"
            customer.save(update_fields=["customer_code"])

    for index, order in enumerate(Order.objects.order_by("id"), start=1):
        if order.order_number.startswith("ORD-"):
            parts = order.order_number.split("-")
            date_part = parts[1] if len(parts) > 1 else "20260519"
            order.order_number = f"{date_part}{index:02d}"
            order.save(update_fields=["order_number"])

    next_order_index = Order.objects.count() + 1
    for invoice in SalesInvoice.objects.filter(order__isnull=True).order_by("id"):
        date_part = invoice.invoice_date.strftime("%Y%m%d") if invoice.invoice_date else "20260519"
        order = Order.objects.create(
            order_number=f"{date_part}{next_order_index:02d}",
            customer_id=invoice.customer_id,
            customer_name=invoice.customer_name,
            customer_phone=invoice.customer_phone,
            order_date=invoice.invoice_date,
            subtotal=invoice.subtotal,
            discount_amount=invoice.discount_amount,
            round_off_amount=getattr(invoice, "round_off_amount", 0),
            grand_total=invoice.grand_total,
            paid_amount=invoice.paid_amount,
            due_amount=invoice.due_amount,
            payment_status=invoice.payment_status,
            created_by_id=invoice.created_by_id,
            notes=invoice.notes,
        )
        invoice.order_id = order.id
        invoice.save(update_fields=["order"])
        next_order_index += 1

    for invoice in SalesInvoice.objects.select_related("order").order_by("id"):
        if invoice.order_id:
            invoice_index = list(invoice.order.invoices.order_by("id").values_list("id", flat=True)).index(invoice.id) + 1
            invoice.invoice_number = f"{invoice.order.order_number}{invoice_index}"
            invoice.save(update_fields=["invoice_number"])
        elif invoice.invoice_number.startswith("INV-"):
            parts = invoice.invoice_number.split("-")
            date_part = parts[1] if len(parts) > 1 else "20260519"
            invoice.invoice_number = f"{date_part}{invoice.id:02d}"
            invoice.save(update_fields=["invoice_number"])


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0004_ordersequence_salesinvoice_round_off_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbatch',
            name='batch_number',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.RunPython(normalize_visible_ids, migrations.RunPython.noop),
    ]
