# Generated by Django 6.0.5 on 2026-05-20 09:29

import pharmacy.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0006_appsetting_printer_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadeddocument',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='uploadeddocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=pharmacy.models.receipt_path, validators=[pharmacy.models.validate_receipt_file]),
        ),
    ]
