# Generated by Django 5.2.14 on 2026-05-18 11:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(default='Pharmacy ERP', max_length=120)),
                ('business_phone', models.CharField(blank=True, max_length=40)),
                ('business_email', models.EmailField(blank=True, max_length=254)),
                ('business_address', models.CharField(blank=True, max_length=255)),
                ('invoice_prefix', models.CharField(default='INV', max_length=10)),
                ('invoice_footer_note', models.CharField(blank=True, default='Thank you for shopping with us.', max_length=255)),
                ('show_logo_on_print', models.BooleanField(default=True)),
                ('low_stock_threshold', models.PositiveIntegerField(default=10)),
                ('near_expiry_days', models.PositiveIntegerField(default=60)),
                ('default_tax_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('currency_symbol', models.CharField(default='৳', max_length=8)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Application Setting',
                'verbose_name_plural': 'Application Settings',
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=60)),
                ('target', models.CharField(blank=True, max_length=120)),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
